### ISSUE TITLE
Add file storage access instructions for Mac

### ISSUE THREAD

**Issue by stevenkbennett** [lukasturcani/stk-vis#14]
stk-vis doesn't work automatically on the latest MacOS version (11.2.3) due to file storage access. Maybe in the instructions there could be a guide to giving stk-vis full file storage access from the accessibility options.

**Comment by lukasturcani** [comment]
Thanks for alerting me to this!!!

**Comment by lukasturcani** [comment]
This should be fixed in the new release https://github.com/lukasturcani/stk-vis/releases/tag/v2021.03.20
