### ISSUE TITLE
Aromaticity

### ISSUE THREAD

**Issue by zjmyfmyf** [lukasturcani/stk-vis#17]
Nice software!
But it seems that the software can't visualize well to molecules with aromaticity. Is it a bug, or it's just my error by not operating appropriately?
![捕获](https://user-images.githubusercontent.com/37296895/115029751-e1110880-9ef8-11eb-999a-3e94fb4c321b.PNG)

**Comment by lukasturcani** [comment]
Hi there! How did you deposit the molecules into the database? Off the top of my head, `stk` should kekulize all molcecules, so convert any aromatics into a kekule representation. If you somehow managed to get a `stk` molecule which is not kekulized, then I think thats a bug in stk.

**Comment by zjmyfmyf** [comment]
Thanks for your advice! I forgot to kekulize it.

**Comment by lukasturcani** [comment]
Np, but I think if your are depositing it into the database via `stk`, you should not have to. `stk` should do it for you. So if it did not, I'd be really interested to see how you deposited the molecules, to see how it was missed.
