### ISSUE TITLE
Can't visualize the created properties

### ISSUE THREAD

**Issue by pumachu** [lukasturcani/stk-vis#22]
Dear Lukas,

Many thanks for developing this exciting tool!
I manage to create a cloud database and use stk-vis to visualize it.
I try to put properties into the database using ValueMongoDb, and I manage to retrieve it using get().
But I can't visualize the property column in stk-vis, only InChlKey is shown.

![image](https://user-images.githubusercontent.com/72870425/117928598-147a6380-b2fc-11eb-94cc-9dbcf4420c97.png)

Below is my test python code, I didn't put the client information.

db = stk.MoleculeMongoDb(
    mongo_client=client,
    # All of the parameters below are optional!
    database='stk-test',
    molecule_collection='molecules',
    position_matrix_collection='building_block_position_matrices'
)

property_db = stk.ValueMongoDb(client,'dipole')
energy_db = stk.ValueMongoDb(client,'energy')

# Create some molecule. "BuildingBlock" is just stk's word for a
# plain molecule.
molecule1 = stk.BuildingBlock('CCCBr')

# Place it into the database, this will make the molecule
# immediately viewable in stk-vis.
db.put(molecule1)
property_db.put(molecule1 , 5.0)
energy_db.put(molecule1 , -10.0)

num_atoms_db = stk.ValueMongoDb(client, 'Num Atoms')

# Place a value associated with the molecule into the database,
# this will make it immediately viewable in stk-vis.
num_atoms_db.put(molecule1, molecule1.get_num_atoms())

#dipole = property_db.get(molecule1)

#print (dipole)

**Comment by pumachu** [comment]
I found the problem.
In my case, I need to specify the database in ValueMongoDb()

**Comment by lukasturcani** [comment]
Glad you got it sorted! Let me know if you run into any other problems.
